spring:
  application:
    name: spring-eureka-client

server:
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.6:9090/eureka

student:
  name: "zhangsan"
  address: "shijiazhuang"