spring:
  application:
    name: springboot-config-server
  cloud:
    config:
      label: test
      profile: default
      username: user
      password: 123123
      discovery:
        enabled: true
        service-id: springboot-config-server
  config:
    import: optional:configserver:springboot-config-server


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.6:9090/eureka
server:
  port: 8090


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true